# ConfigMap para la configuración de n8n
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: default
data:
  config: |
    {
      "encryptionKey": "vySGs7SRi+/Kh7QO8Q+JekO+OtC4gTnq"
    }