# Secret para credenciales sensibles
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: default
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "admin123"
  DB_POSTGRESDB_USER: "dml"
  DB_POSTGRESDB_PASSWORD: "Sergio55"