# evolution-pvc.yaml (CORREGIDO)

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evolution-instances-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path  # <--- ¡ESTA ES LA LÍNEA CLAVE!