
apiVersion: v1
kind: Service
metadata:
  name: evolution-api-service
  labels:
    app: evolution-api
spec:
  selector:
    app: evolution-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP

