# Cloudflare Tunnel - Túnel compartido para ambas empresas
# Namespace: shared

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: shared
type: Opaque
stringData:
  tunnel-token: eyJhIjoiMzRhZDRkMjRlYjIyMDVjMGEyZWNhMjcwOTZlYzliY2UiLCJ0IjoiODNhMmU0MjEtMmI3MC00ZWEzLWEzMGUtNzA1ZWE3YmNjZjM2IiwicyI6Ill6VTJObUUwTVRjdE1XSTBPQzAwT1dRMExXSTFZelV0TTJaak5EZGxOekUzT0dFdyJ9

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: shared
data:
  config.yml: |
    tunnel: 83a2e421-2b70-4ea3-a30e-705ea7bccf36
    credentials-file: /etc/cloudflared/creds/credentials.json

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: shared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config.yml
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: tunnel-token
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: cloudflared-config
          configMap:
            name: cloudflared-config
      restartPolicy: Always
