apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data19e
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  #storageClassName: do-block-storage
