# Portal de Facturaci贸n - Aplicaci贸n Flask para DML
# Namespace: dml
# Conexi贸n a BD: postgres-nodeport.infrastructure.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: portal-facturacion-secret
  namespace: dml
type: Opaque
stringData:
  # PostgreSQL password
  POSTGRES_PASSWORD: "Sergio55"
  # Odoo password
  ODOO_PASSWORD: "TuPasswordDeOdoo"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-facturacion-config
  namespace: dml
  labels:
    app: portal-facturacion
data:
  UPLOAD_FOLDER: "/app/uploads"
  # CAMBIO CLAVE: Conexi贸n a postgres en namespace infrastructure
  POSTGRES_HOST: "postgres-nodeport.infrastructure.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mercadoLibre"
  POSTGRES_USER: "dml"
  N8N_WEBHOOK_URL: "https://aut.automateai.com.mx/webhook/a86064e4-d5ef-4abe-85cd-be0362757f88"
  N8N_DOWNLOAD_WEBHOOK_URL: "https://aut.automateai.com.mx/webhook/archivos-facturacion"
  ODOO_URL: "https://dml-medica.com/"
  ODOO_DB: "Dml-Medica"
  ODOO_USERNAME: "automatizaciones@dml-medica.com"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-facturacion-uploads
  namespace: dml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-facturacion
  namespace: dml
  labels:
    app: portal-facturacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-facturacion
  template:
    metadata:
      labels:
        app: portal-facturacion
    spec:
      containers:
        - name: flask-app
          image: proyectosspr/portal-facturacion:1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: portal-facturacion-config
            - secretRef:
                name: portal-facturacion-secret
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: portal-facturacion-uploads
      restartPolicy: Always
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: portal-facturacion
  namespace: dml
spec:
  selector:
    app: portal-facturacion
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
