# Odoo 16 DML - Instancia de desarrollo para DML
# Namespace: dml
# Conexión a BD: postgres-nodeport.infrastructure.svc.cluster.local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data16
  namespace: dml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-extra-addons16
  namespace: dml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons16
  namespace: dml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config16
  namespace: dml
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons/modulos_odoo16
    admin_passwd = 123456
    csv_internal_sep = ,
    data_dir = /var/lib/odoo
    # CAMBIO CLAVE: Conexión a postgres en namespace infrastructure
    db_host = postgres-nodeport.infrastructure.svc.cluster.local
    db_maxconn = 64
    db_port = 5432
    db_sslmode = prefer
    db_template = template1
    db_user = dml
    db_name = dml
    db_password = Sergio55
    demo = {}
    email_from = proyectos_spr@outlook.com

    http_interface = 0.0.0.0
    http_port = 8069
    gevent_port = 8072
    workers = 5
    max_cron_threads = 1

    limit_memory_hard = 2684354560
    limit_memory_soft = 2147483648
    limit_request = 8192
    limit_time_cpu = 120
    limit_time_real = 300
    limit_time_real_cron = 600

    proxy_mode = true
    secure_cookie_httponly = true

    list_db = True
    log_db = True
    log_db_level = warning
    log_level = info
    logfile = False

    server_wide_modules = base,web
    timezone = America/Mexico_City

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo16
  namespace: dml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo16
  template:
    metadata:
      labels:
        app: odoo16
    spec:
      securityContext:
        fsGroup: 101
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "chown -R 101:101 /var/lib/odoo /mnt/extra-addons && chmod -R 775 /var/lib/odoo /mnt/extra-addons",
            ]
          volumeMounts:
            - name: odoo-data16
              mountPath: /var/lib/odoo
            - name: odoo-extra-addons16
              mountPath: /mnt/extra-addons
      containers:
        - name: odoo16
          image: proyectosspr/odoo_16_git:1.8-claude
          imagePullPolicy: Always
          command: ["/usr/bin/odoo"]
          args:
            - "--config=/etc/odoo/odoo.conf"
            - "--limit-time-cpu=8200"
            - "--limit-time-real=8200"
            - "--dev=all"
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          ports:
            - containerPort: 8069
              name: http
            - containerPort: 8072
              name: longpolling
          env:
            - name: HTTP_X_FORWARDED_PROTO
              value: "https"
            - name: HTTP_X_FORWARDED_HOST
              value: "automateai.com.mx"
            - name: HTTP_X_FORWARDED_PORT
              value: "443"
            - name: HOST
              value: "automateai.com.mx"
          volumeMounts:
            - name: odoo-data16
              mountPath: /var/lib/odoo
            - name: config-volume16
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons16
              mountPath: /mnt/extra-addons
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "15Gi"
              cpu: "15"

        - name: jupyter
          image: proyectosspr/odoo_16_git:1.8-claude
          imagePullPolicy: Always
          command: ["jupyter", "lab"]
          args:
            - "--ip=0.0.0.0"
            - "--port=8888"
            - "--ServerApp.token=admin"
            - "--notebook-dir=/mnt/extra-addons"
            - "--no-browser"
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          ports:
            - containerPort: 8888
              name: jupyter
          volumeMounts:
            - name: odoo-data16
              mountPath: /var/lib/odoo
            - name: config-volume16
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons16
              mountPath: /mnt/extra-addons
      volumes:
        - name: odoo-data16
          persistentVolumeClaim:
            claimName: odoo-data16
        - name: config-volume16
          configMap:
            name: odoo-config16
            items:
              - key: odoo.conf
                path: odoo.conf
        - name: odoo-extra-addons16
          persistentVolumeClaim:
            claimName: odoo-extra-addons16

---
apiVersion: v1
kind: Service
metadata:
  name: odoo16
  namespace: dml
spec:
  selector:
    app: odoo16
  ports:
    - protocol: TCP
      name: http
      port: 8069
      targetPort: 8069
    - protocol: TCP
      name: longpolling
      port: 8072
      targetPort: 8072
    - protocol: TCP
      name: jupyter
      port: 8888
      targetPort: 8888
  type: ClusterIP
