apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: cHJveWVjdG9zX3NwckBvdXRsb29rLmNvbQ==  # proyectos_spr@outlook.com
  PGADMIN_DEFAULT_PASSWORD: U2VyZ2lvNTU=   # Sergio55
