apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30080  # puedes elegir un puerto entre 30000-32767
