apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo18
  template:
    metadata:
      labels:
        app: odoo18
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: odoo18
          image: proyectosspr/odoo:git
          ports:
            - containerPort: 8069
            - containerPort: 8888
            - containerPort: 8072 
          env:
            - name: HTTP_X_FORWARDED_PROTO
              value: "https"
            - name: HTTP_X_FORWARDED_HOST
              value: "odoo.automateai.com.mx"
            - name: HTTP_X_FORWARDED_PORT
              value: "443"
            - name: HOST
              value: "odoo.automateai.com.mx"
          
          volumeMounts:
            - name: odoo-data18
              mountPath: /var/lib/odoo
            - name: config-volume18
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons18
              mountPath: /mnt/extra-addons   # 🔹 Aquí montamos tu carpeta de módulos extra
          
          resources:
            requests:
              memory: "3Gi"
              cpu: "2"
            limits:
              memory: "5Gi"
              cpu: "3"
      volumes:
        - name: odoo-data18
          persistentVolumeClaim:
            claimName: odoo-data18
        - name: config-volume18
          configMap:
            name: odoo-config18
            items:
              - key: odoo.conf
                path: odoo.conf
        - name: odoo-extra-addons18
          persistentVolumeClaim:
            claimName: odoo-extra-addons18
