apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo18
  template:
    metadata:
      labels:
        app: odoo18
    spec:
      securityContext:
        fsGroup: 101

      initContainers:
      - name: fix-permissions
        image: busybox:latest
        # Comando reforzado: asegura propietario y permisos de escritura en cada arranque.
        command: ["sh", "-c", "chown -R 101:101 /var/lib/odoo /mnt/extra-addons && chmod -R 775 /var/lib/odoo /mnt/extra-addons"]
        volumeMounts:
          - name: odoo-data18
            mountPath: /var/lib/odoo
          - name: odoo-extra-addons18
            mountPath: /mnt/extra-addons

      containers:
        - name: odoo18
          # Asegúrate de que este sea el tag de tu imagen corregida.
          image: proyectosspr/odoo_18_git:3.0
          # Forza a Kubernetes a descargar siempre la última versión de la imagen.
          imagePullPolicy: Always 
          
          # Se elimina el 'command' y 'args' de 'sleep' para que el pod use el CMD del Dockerfile.
          # Se elimina el 'securityContext' con 'runAsUser' porque el Dockerfile ya lo gestiona.

          ports:
            - containerPort: 8069
            - containerPort: 8888
            - containerPort: 8072 
          env:
            - name: HTTP_X_FORWARDED_PROTO
              value: "https"
            - name: HTTP_X_FORWARDED_HOST
              value: "odoo.automateai.com.mx"
            - name: HTTP_X_FORWARDED_PORT
              value: "443"
            - name: HOST
              value: "odoo.automateai.com.mx"
          
          volumeMounts:
            - name: odoo-data18
              mountPath: /var/lib/odoo
            - name: config-volume18
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons18
              mountPath: /mnt/extra-addons
          
          resources:
            requests:
              memory: "4Gi"
              cpu: "3"
            limits:
              memory: "6Gi"
              cpu: "4"

      volumes:
        - name: odoo-data18
          persistentVolumeClaim:
            claimName: odoo-data18
        - name: config-volume18
          configMap:
            name: odoo-config18
            items:
              - key: odoo.conf
                path: odoo.conf
        - name: odoo-extra-addons18
          persistentVolumeClaim:
            claimName: odoo-extra-addons18