apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo18
  template:
    metadata:
      labels:
        app: odoo18
    spec:
      securityContext:
        fsGroup: 101

      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh", "-c", "chown -R 101:101 /var/lib/odoo /mnt/extra-addons && chmod -R 775 /var/lib/odoo /mnt/extra-addons"]
        volumeMounts:
          - name: odoo-data18
            mountPath: /var/lib/odoo
          - name: odoo-extra-addons18
            mountPath: /mnt/extra-addons

      containers:
        - name: odoo18
          image: proyectosspr/odoo_18_git:4.2
          imagePullPolicy: Always 
          
          # ==== ¡ESTA ES LA CORRECCIÓN CLAVE! ====
          # Se sobreescribe el comando de arranque para forzar el puerto de longpolling correcto.
          # Esto tiene más prioridad que cualquier configuración en el Dockerfile o en odoo.conf.
          command: ["bash", "-c"]
          args:
            - "odoo -c /etc/odoo/odoo.conf & jupyter lab --ip=0.0.0.0 --port=8888 --ServerApp.token=admin --notebook-dir=/opt/jupyter --no-browser"
          
          ports:
            # Puertos que realmente se están usando. Se elimina el 8072 que causaba el conflicto.
            - containerPort: 8069 # Odoo Web
            - containerPort: 8888 # Jupyter Lab
            - containerPort: 8072 # <--- CORRIGE ESTE PUERTO
              name: longpolling # Odoo Longpolling
              
          
          env:
            - name: HTTP_X_FORWARDED_PROTO
              value: "https"
            - name: HTTP_X_FORWARDED_HOST
              value: "automateai.com.mx"
            - name: HTTP_X_FORWARDED_PORT
              value: "443"
            - name: HOST
              value: "automateai.com.mx"
          
          volumeMounts:
            - name: odoo-data18
              mountPath: /var/lib/odoo
            - name: config-volume18
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons18
              mountPath: /mnt/extra-addons
          
          resources:
            requests:
              memory: "4Gi"
              cpu: "3"
            limits:
              memory: "6Gi"
              cpu: "4"

      volumes:
        - name: odoo-data18
          persistentVolumeClaim:
            claimName: odoo-data18
        - name: config-volume18
          configMap:
            name: odoo-config18
            items:
              - key: odoo.conf
                path: odoo.conf
        - name: odoo-extra-addons18
          persistentVolumeClaim:
            claimName: odoo-extra-addons18