# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: odoo18
spec:
  selector:
    app: odoo18
  ports:
    - protocol: TCP
      name: http
      port: 8069 
      targetPort: 8069
    - protocol: TCP
      name: jupyter
      port: 8888
      targetPort: 8888
    - protocol: TCP
      name: longpolling # <--- AÑADE ESTA SECCIÓN
      port: 8072
      targetPort: 8072
  type: ClusterIP