apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
type: Opaque
stringData:
  # Token original (Kubernetes lo codifica automáticamente)
  tunnel-token: eyJhIjoiMzRhZDRkMjRlYjIyMDVjMGEyZWNhMjcwOTZlYzliY2UiLCJ0IjoiN2FiZjkxMWQtNjZhOS00NDA4LTg2MzgtMzBkY2UzZDgzY2NiIiwicyI6Ik5UYzJZMkl3TTJJdE56TTROeTAwWm1VekxXSmxaamd0WlRRMVpEVTNNekV3TkdGaCJ9
