apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
type: Opaque
stringData:
  # Token original (Kubernetes lo codifica automáticamente)
  tunnel-token: eyJhIjoiMzRhZDRkMjRlYjIyMDVjMGEyZWNhMjcwOTZlYzliY2UiLCJ0IjoiYzNjOTI4ZDEtY2E2OS00MmM3LTk0YTctODAyNDQzOWI5NTA4IiwicyI6Ik4yWm1ZMlUwWkRFdE1XRTRNQzAwTXpkbExXSXpPRGt0WWpJek5tTXpaV1poWkRBeSJ9