# N8N AutomateAI - Automatización de workflows para AutomateAI
# Namespace: automateai
# Conexión a BD: postgres-nodeport.infrastructure.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-automateai-secrets
  namespace: automateai
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "admin123"
  DB_POSTGRESDB_USER: "dml"
  DB_POSTGRESDB_PASSWORD: "Sergio55"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-automateai-config
  namespace: automateai
data:
  config: |
    {
      "encryptionKey": "vySGs7SRi+/Kh7QO8Q+JekO+OtC4gTnq"
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-automateai-data-pvc
  namespace: automateai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-automateai
  namespace: automateai
  labels:
    app: n8n-automateai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-automateai
  template:
    metadata:
      labels:
        app: n8n-automateai
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          chown -R 1000:1000 /home/node/.n8n
          chmod -R 755 /home/node/.n8n
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        securityContext:
          runAsUser: 0
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
          name: http
        env:
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: n8n-automateai-secrets
              key: N8N_BASIC_AUTH_USER
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-automateai-secrets
              key: N8N_BASIC_AUTH_PASSWORD
        - name: N8N_HOST
          value: "0.0.0.0"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: WEBHOOK_URL
          value: "http://n8n.automateai.com.mx:5678"
        - name: GENERIC_TIMEZONE
          value: "America/Mexico_City"
        # CAMBIO CLAVE: Conexión a postgres en namespace infrastructure
        - name: DB_TYPE
          value: "postgresdb"
        - name: DB_POSTGRESDB_HOST
          value: "postgres-nodeport.infrastructure.svc.cluster.local"
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_DATABASE
          value: "n8n_automateai"
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: n8n-automateai-secrets
              key: DB_POSTGRESDB_USER
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-automateai-secrets
              key: DB_POSTGRESDB_PASSWORD
        - name: N8N_ENCRYPTION_KEY
          value: "vySGs7SRi+/Kh7QO8Q+JekO+OtC4gTnq"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        - name: n8n-config-volume
          mountPath: /home/node/.n8n/config
          subPath: config
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "5Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-automateai-data-pvc
      - name: n8n-config-volume
        configMap:
          name: n8n-automateai-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-automateai
  namespace: automateai
spec:
  type: NodePort
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
    nodePort: 30678
  selector:
    app: n8n-automateai
