# Odoo 19 - Instancia de producción para AutomateAI
# Namespace: automateai
# Conexión a BD: postgres-nodeport.infrastructure.svc.cluster.local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data19
  namespace: automateai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-extra-addons19
  namespace: automateai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config19
  namespace: automateai
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons/modulos_odoo19 , /mnt/extra-addons/enterprise_19
    admin_passwd = 123456
    csv_internal_sep = ,
    data_dir = /var/lib/odoo
    # CAMBIO CLAVE: Conexión a postgres en namespace infrastructure
    db_host = postgres-nodeport.infrastructure.svc.cluster.local
    db_maxconn = 64
    db_port = 5432
    db_sslmode = prefer
    db_template = template1
    db_user = dml
    db_name = odoo19
    db_password = Sergio55
    demo = {}
    email_from = proyectos_spr@outlook.com

    # Configuración HTTP principal
    http_interface = 0.0.0.0
    http_port = 8069

    # Configuración de longpolling
    gevent_port = 8072

    # Workers configuration
    workers = 5
    max_cron_threads = 1

    # Limites de recursos
    limit_memory_hard = 2684354560
    limit_memory_soft = 2147483648
    limit_request = 8192
    limit_time_cpu = 120
    limit_time_real = 300
    limit_time_real_cron = 600

    # Proxy y seguridad
    proxy_mode = true
    secure_cookie_httponly = true

    # Database settings
    list_db = True
    log_db = True
    log_db_level = warning
    log_level = info
    logfile = False

    # Modules
    server_wide_modules = base,web

    # Timezone
    timezone = America/Mexico_City

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo19
  namespace: automateai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo19
  template:
    metadata:
      labels:
        app: odoo19
    spec:
      securityContext:
        fsGroup: 101
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "chown -R 101:101 /var/lib/odoo /mnt/extra-addons && chmod -R 775 /var/lib/odoo /mnt/extra-addons",
            ]
          volumeMounts:
            - name: odoo-data19
              mountPath: /var/lib/odoo
            - name: odoo-extra-addons19
              mountPath: /mnt/extra-addons
      containers:
        - name: odoo19
          image: proyectosspr/odoo19e:1.0
          imagePullPolicy: Always
          command: ["/usr/bin/odoo"]
          args:
            - "--config=/etc/odoo/odoo.conf"
            - "--dev=all"
          ports:
            - containerPort: 8069
              name: http
            - containerPort: 8072
              name: longpolling
          env:
            - name: HTTP_X_FORWARDED_PROTO
              value: "https"
            - name: HTTP_X_FORWARDED_HOST
              value: "automateai.com.mx"
            - name: HTTP_X_FORWARDED_PORT
              value: "443"
            - name: HOST
              value: "automateai.com.mx"
          volumeMounts:
            - name: odoo-data19
              mountPath: /var/lib/odoo
            - name: config-volume19
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons19
              mountPath: /mnt/extra-addons
          resources:
            requests:
              memory: "4Gi"
              cpu: "3"
            limits:
              memory: "6Gi"
              cpu: "4"

        - name: jupyter
          image: proyectosspr/odoo19e:1.0
          imagePullPolicy: Always
          command: ["jupyter", "lab"]
          args:
            - "--ip=0.0.0.0"
            - "--port=8888"
            - "--ServerApp.token=admin"
            - "--notebook-dir=/mnt/extra-addons"
            - "--no-browser"
            - "--allow-root"
          ports:
            - containerPort: 8888
              name: jupyter
          volumeMounts:
            - name: odoo-data19
              mountPath: /var/lib/odoo
            - name: config-volume19
              mountPath: /etc/odoo
              readOnly: true
            - name: odoo-extra-addons19
              mountPath: /mnt/extra-addons
      volumes:
        - name: odoo-data19
          persistentVolumeClaim:
            claimName: odoo-data19
        - name: config-volume19
          configMap:
            name: odoo-config19
            items:
              - key: odoo.conf
                path: odoo.conf
        - name: odoo-extra-addons19
          persistentVolumeClaim:
            claimName: odoo-extra-addons19

---
apiVersion: v1
kind: Service
metadata:
  name: odoo19
  namespace: automateai
spec:
  selector:
    app: odoo19
  ports:
    - protocol: TCP
      name: http
      port: 8069
      targetPort: 8069
    - protocol: TCP
      name: longpolling
      port: 8072
      targetPort: 8072
    - protocol: TCP
      name: jupyter
      port: 8888
      targetPort: 8888
  type: ClusterIP
