apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  labels:
    app: nginx-proxy-manager
spec:
  type: ClusterIP
  selector:
    app: nginx-proxy-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: admin
      port: 81
      targetPort: 81
      protocol: TCP