apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-letsencrypt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  #storageClassName: do-block-storage